### ISSUE TITLE
`Sleep Page`: Create a Label that will show the amount of time you are sleeping

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#10]
- Create lable that will be showing time duration that tracked by Start/Stop sleeping, use [figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0-1) as a reference 

Issue is completed when:
1. Lable looks like Figma representation
2. Lable show time interval between current time and alarm time (expl. c.t. 22:00 - a.t. 06:00 -> lable time 08:0)

**Comment by marinkman** [comment]
It is not clear how it should look and where it should be.
You need to either write it or give a link to the figma.
