### ISSUE TITLE
`Sleep Page`: Create screen change logic to the `During Sleep Page` screen

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#11]
### DoD:

- when you press the `start sleeping` button on the `Sleep Page` screen, the `Sleep Page` screen changes to the `During Sleep Page` screen.

See `First sprint` in [figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0-1&t=tBp7chY4yTtEapBF-0).

**Comment by MikhailKosarev** [comment]
Will it be different screen or the same?

**Comment by nek-to** [comment]
What does it mean's `change`?
Transfer to another screen or redraw current view?
We discuss about it today but I had to leave.
