### ISSUE TITLE
`During Sleep`: Change the picture 

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#12]
### DoD:

- when the `Sleep Page` screen changes to the `During Sleep Page` screen, the `astronaut` picture changes to the `sleeping astronaut` picture.

See `First sprint` in [figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0-1&t=tBp7chY4yTtEapBF-0).

**Comment by MikhailKosarev** [comment]
can we combine it with task #11?

**Comment by nek-to** [comment]
Look's like a part of issue #9 logic. Correct me if I'm wrong.
