### ISSUE TITLE
`During Sleep`: Add logic to change the button to `Stop Sleeping`

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#13]
### DoD:

- when the `Sleep Page` screen changes to the `During Sleep Page` screen, the `start sleeping` button changes to the `stop sleeping` button.

See `First sprint` in [figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0-1&t=tBp7chY4yTtEapBF-0).

**Comment by MikhailKosarev** [comment]
combine with #11?
