### ISSUE TITLE
`Sleep Report`: add a label with the name `Sleep Report`

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#17]
### DoD:

create a label on which Sleep Report will be written in the upper right corner, the exact location can be seen in [Figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0%3A1&t=LvXBgxbT97WA1wUw-1)

**Comment by MikhailKosarev** [comment]
as a separate view?

**Comment by meschya** [comment]
> as a separate view?

No, just the text on the right side of the main view
