### ISSUE TITLE
Create `RoundedRectangleView` 

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#22]
### DoD:

create `RoundedRectangleView` that can change its title, the design of the rectangle can be viewed in [Figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0%3A1&t=9Jf97CaFnqWDDYri-1)

### Depend on:

#1 #28

**Comment by marinkman** [comment]
Depend on #5
