### ISSUE TITLE
`DuringSleepView`: create a view

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#24]
### DoD: 

create a `DuringSleepView`, the view layout can be viewed in [Figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0%3A1&t=9Jf97CaFnqWDDYri-1)

### Depend on: 

#1 #28

**Comment by marinkman** [comment]
Depend on https://github.com/ios-course/swiftcowboys-team-project/issues/5
