### ISSUE TITLE
`SleepPageView`: сreate a screen and implementing logic 

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#25]
### DoD:

Create a `SleepPageView` screen as shown in [Figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0%3A1&t=9Jf97CaFnqWDDYri-1)

Features:
- Add `SleepView` and `DuringSleepView` to the screen, but `DuringSleepView` is hide.
- When clicking on `Start Sleep` button, hide `SleepView` and show `DuringSleepView`.
- When clicking on `Start Sleep` button, the title of button should change to `Stop Sleeping`.

### Depend on: 
#22 #23 #24

**Comment by marinkman** [comment]
Duplicated of #45
