### ISSUE TITLE
Create a file with the color scheme used in Wiki

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#3]
### DoD:
Take all the colors used in the project from [figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0-1) and add to the file in Wiki `Project color scheme` in the particular format.

#### Format of colors:
nameOfColor = Color(red: 79.0 / 255, green: 79.0 / 255, blue: 191.0 / 255)

**Comment by MikhailKosarev** [comment]
and create the same file in Wiki of the project?

**Comment by MikhailKosarev** [comment]
What format will we use?
`nameOfColor = Color(red: 79.0 / 255, green: 79.0 / 255, blue: 191.0 / 255)`

**Comment by MikhailKosarev** [comment]
And where will be the file?

**Comment by meschya** [comment]
> and create the same file in Wiki of the project?

I think so, yes.

**Comment by meschya** [comment]
> What format will we use? `nameOfColor = Color(red: 79.0 / 255, green: 79.0 / 255, blue: 191.0 / 255)`

We can also use #imageLiteral, I think you will like it 😉

**Comment by meschya** [comment]
> And where will be the file?

I used to create a separate `Colors` file for this, with the usual `enum`

**Comment by MikhailKosarev** [comment]
@marinkman yeah, this task is about Wiki. Fixed the description

**Comment by marinkman** [comment]
OK, then we don't have a task for the `Color` file in the project?

**Comment by MikhailKosarev** [comment]
you're right. We need another task for file in the proejct

**Comment by MikhailKosarev** [comment]
@marinkman add #28

**Comment by nek-to** [comment]
Reviewed: Done!
