### ISSUE TITLE
Add pictures from figma 

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#4]
### DoD:
- Take all the images used in the project from [figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0-1) and add to the project assets.
Note: You can make up your own names, but they should make sense.

### Depend on: 
#1

**Comment by marinkman** [comment]
Names should not be the same as in Figma.

**Comment by MikhailKosarev** [comment]
@marinkman fixed the description
