### ISSUE TITLE
Creating a project architecture 

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#5]
### DoD:
- Add project structure. Use MVVM architecture and organize code by layers. Create 3 directories: Model, View, ViewModel.
### Depend on: 
#1

**Comment by MikhailKosarev** [comment]
we should decide what the files we need to create

**Comment by meschya** [comment]
## `Model`
 I think to skip it for now 
## `View` 
- SleepPage 
- DuringSleep 
- SleepReport
- CustomSleepButton
- AlarmButton
## `ViewModel` 
- SleepPageViewModel
- DuringSleepViewModel
- SleepReportViewModel
## `Colors`
The folder with the file where the enum with colors will be stored

**Comment by MikhailKosarev** [comment]
I suggest using folder `Helpers` with file `Color` instead of folder `Colors`

**Comment by MikhailKosarev** [comment]
`SleepPage` and `DuringSleep` are the same?

**Comment by nek-to** [comment]
So where is the right structure:
 [At the top](https://github.com/ios-course/swiftcowboys-team-project/issues/5#issue-1689553256) or [here](https://github.com/ios-course/swiftcowboys-team-project/issues/5#issuecomment-1533765206)?

**Comment by MikhailKosarev** [comment]
The actual information to check on top always. In comments there is just a discussion.

**Comment by nek-to** [comment]
K, coz it doesn't look's like suggested.
Thanks for the clarification.

**Comment by meschya** [comment]
Incorrect issue
