### ISSUE TITLE
`Sleep Button`: create button

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#6]
### DoD:

- Create a custom button that can change its title, the button layout can be viewed in [Figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0%3A1&t=9Jf97CaFnqWDDYri-1)
- Made navigation when button is tapped using scheme in [Figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0%3A1&t=9Jf97CaFnqWDDYri-1)

Issue is completed when:
1. Button looks like Figma representation
2. When you press it, the screen changes according to the scheme

### Depend on:

#1

**Comment by marinkman** [comment]
At this stage we will not have animation.

**Comment by MikhailKosarev** [comment]
I suggest using the default settings for this button now.

**Comment by MikhailKosarev** [comment]
What about the background picture? Will we use the picture of just the background color?

**Comment by nek-to** [comment]
> What about the background picture? Will we use the picture of just the background color?

I don't think so. We can use figma model. 
To be honest, I'd rather deal with our own design...
