### ISSUE TITLE
`Sleep Page`: Create a `Start/Stop sleeping` button

### ISSUE THREAD

**Issue by meschya** [ios-course/swiftcowboys-team-project#8]
- Button must rotate cosmonaut icon as on [Figma](https://www.figma.com/file/Q3Vq556r3LTQrOokAggk1Z/Sleep-Magic-App-Design?node-id=0-1) to show current state (sleep or not)
- Button must redirect to another view (look at the Figma scheme)
- Button should change self lable statement (Start/Stop Sleeping) by tap

Issue is completed when:
- Press on the button correctly redirect
- Press on the button rotate cosmonaut corractly

**Comment by marinkman** [comment]
At this stage we will not have animation.

**Comment by MikhailKosarev** [comment]
And at this stage we don't have any calculations, just a screen, right?

**Comment by nek-to** [comment]
I still didn't get what should we have at the end: just done screens or screens with logic
